included:
  - Sources

disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - identifier_name
  - trailing_comma
  - vertical_whitespace
  - inclusive_language
  - large_tuple
  - unused_closure_parameter
  - for_where
